server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Редирект со старых путей /frontend/... на корень
    location = /frontend {
        return 301 /;
    }

    location /frontend/ {
        rewrite ^/frontend/(.*)$ /$1 permanent;
    }
}
